require:
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'test/**/*'
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/environments/*'
    - 'config/puma.rb'
    - 'config/initializers/*'

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/application_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/HashSyntax:
  Enabled: false


#差し当たり
Rails/I18nLocaleTexts:
  Enabled: false
