# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Conversation.create!(level:3, content:"（えもん）・・・むずかしいダ。", speaker:1, order:1)
Conversation.create!(level:3, content:"（ ぼく ）どうしたの？", speaker:0, order:2)
Conversation.create!(level:3, content:"（えもん）この小さい「ぁ」ダ。", speaker:1, order:3)
Conversation.create!(level:3, content:"（えもん）「疲れて何もしたくない時の顔を想像して、口を開けずに軽く『ぁ』」", speaker:1, order:4)
Conversation.create!(level:3, content:"（えもん）ってどういうことダ？", speaker:1, order:5)
Conversation.create!(level:3, content:"（ ぼく ）うーん、そうだなあ。", speaker:0, order:6)
Conversation.create!(level:3, content:"（ ぼく ）『英語えもん、今日英語えもんがそうじ当番だよ。覚えてるよね？』", speaker:0, order:7)
Conversation.create!(level:3, content:"（えもん）ぁ（めんどくさい）。", speaker:1, order:8)
Conversation.create!(level:3, content:"（ ぼく ）いまの「ぁ」の音だよ。", speaker:0, order:9)
Conversation.create!(level:3, content:"（えもん）りかいしたダ。", speaker:1, order:10)

Conversation.create!(level:4, content:"（えもん）・・・ナットクいかないダ。", speaker:1, order:1)
Conversation.create!(level:4, content:"（ ぼく ）どうしたの？", speaker:0, order:2)
Conversation.create!(level:4, content:"（えもん）「hub」は「はぶ」だったから", speaker:1, order:3)
Conversation.create!(level:4, content:"（えもん）気を利かせて「push」を「ぱっしゅ」って読んだら違ったダ。", speaker:1, order:4)
Conversation.create!(level:4, content:"（ ぼく ）なるほどね。", speaker:0, order:5)
Conversation.create!(level:4, content:"（ ぼく ）たしか昔はいまよりも 英語をそのままローマ字読みしてたらしいんだ。", speaker:0, order:6)
Conversation.create!(level:4, content:"（ ぼく ）たぶん文字を書くよりも 音声で話すことのほうが一般的だから", speaker:0, order:7)
Conversation.create!(level:4, content:"（ ぼく ）発音だけはどんどんやりやすいように変化していって", speaker:0, order:8)
Conversation.create!(level:4, content:"（ ぼく ）文字の表記は わざわざそれに合わせて修正しなかったみたいだよ。", speaker:0, order:9)
Conversation.create!(level:4, content:"（えもん）なるほどダ。ナットクするしかなさそうな話なんダナ。", speaker:1, order:10)
Conversation.create!(level:4, content:"（ ぼく ）（まったくナットクしてないらしい）", speaker:0, order:11)

Conversation.create!(level:5, content:"（ ぼく ）ねえ英語えもん、ふと思ったんだけど、", speaker:0, order:1)
Conversation.create!(level:5, content:"（ ぼく ）ふりがないんぐりっしゅ　あまり通じないんじゃない？", speaker:0, order:2)
Conversation.create!(level:5, content:"（えもん）残念ながら　たしかにそんなに通じないダ！", speaker:1, order:3)
Conversation.create!(level:5, content:"（えもん）なんでわかったダ？", speaker:1, order:4)
Conversation.create!(level:5, content:"（ ぼく ）この前も話したけど、たしかこの時代って", speaker:0, order:5)
Conversation.create!(level:5, content:"（ ぼく ）英語の発音が大幅に変化した時代だって", speaker:0, order:6)
Conversation.create!(level:5, content:"（ ぼく ）どこかで聞いた記憶があるんだ。", speaker:0, order:7)
Conversation.create!(level:5, content:"（えもん）なるほどなんダナ。", speaker:1, order:8)
Conversation.create!(level:5, content:"（えもん）日本の時代背景は知ってるダ？", speaker:1, order:9)
Conversation.create!(level:5, content:"（ ぼく ）時代背景？", speaker:0, order:10)
Conversation.create!(level:5, content:"（えもん）キミはいま　夢か現実かはさておき　およそ400年まえにいるダ。", speaker:1, order:11)
Conversation.create!(level:5, content:"（えもん）400年前は　どんな外交をしてたって習ったダ？", speaker:1, order:12)
Conversation.create!(level:5, content:"（ ぼく ）鎖国してオランダと交流してたんだっけ？", speaker:0, order:13)
Conversation.create!(level:5, content:"（えもん）そうだナ！だからキミも言ってたけど　同じ「英語」とはいえ", speaker:1, order:14)
Conversation.create!(level:5, content:"（えもん）現代のアメリカ英語とはずいぶん音や読み方が違うダ。", speaker:1, order:15)
Conversation.create!(level:5, content:"（ ぼく ）そういえばこのときに　カステラとか", speaker:0, order:16)
Conversation.create!(level:5, content:"（ ぼく ）オランダ語も入ってきたって　習った気がするなあ。", speaker:0, order:17)
Conversation.create!(level:5, content:"（えもん）でもおもしろいから　ふりがないんぐりっしゅを学びつづけるダ。", speaker:1, order:18)
Conversation.create!(level:5, content:"（えもん）むしろ令和のアメリカ英語を江戸に広めるっていう", speaker:1, order:19)
Conversation.create!(level:5, content:"（えもん）あらたな野望ができたダ。", speaker:1, order:20)
Conversation.create!(level:5, content:"（ ぼく ）（歴史がおかしなことになっても ぼくはしらないぞ・・・。） ", speaker:0, order:21)

Conversation.create!(level:6, content:"（ ぼく ）ところで英語えもん、帰る準備は進んでいるの？", speaker:0, order:1)
Conversation.create!(level:6, content:"（えもん）じゅんび？", speaker:1, order:2)
Conversation.create!(level:6, content:"（ ぼく ）「じゅんび？」じゃないよ。現代に帰る方法にあてがあるんでしょ？", speaker:0, order:3)
Conversation.create!(level:6, content:"（えもん）うん！モチロンなんダナ！", speaker:1, order:4)
Conversation.create!(level:6, content:"（ ぼく ）どこにでも行けるドアとか", speaker:0, order:5)
Conversation.create!(level:6, content:"（ ぼく ）時空を超越する引き出し付きの机とか", speaker:0, order:6)
Conversation.create!(level:6, content:"（ ぼく ）ぼくもいっしょに作るよ！", speaker:0, order:7)
Conversation.create!(level:6, content:"（えもん）うーん、その方法はたぶんとてもむずかしいダ。", speaker:1, order:8)
Conversation.create!(level:6, content:"（ ぼく ）え、そうなの？", speaker:0, order:9)
Conversation.create!(level:6, content:"（えもん）ワームホールって　知ってるダ？", speaker:1, order:10)
Conversation.create!(level:6, content:"（ ぼく ）わあむほおる？", speaker:0, order:11)
Conversation.create!(level:6, content:"（えもん）入ったら時空を超えて移動できるかもしれないダ。", speaker:1, order:12)
Conversation.create!(level:6, content:"（ ぼく ）じゃあ　まさにあの引き出し付きの机が作れるんじゃないの？", speaker:0, order:13)
Conversation.create!(level:6, content:"（えもん）いや　ワームホールはどこにあるかわからないし", speaker:1, order:14)
Conversation.create!(level:6, content:"（えもん）かりに 入ったとしてもどこに出るかわからないし", speaker:1, order:15)
Conversation.create!(level:6, content:"（えもん）しかもとてつもなく小さくて", speaker:1, order:16)
Conversation.create!(level:6, content:"（えもん）キミを細胞サイズにしたとしても　入れないダ。", speaker:1, order:17)
Conversation.create!(level:6, content:"（ ぼく ）・・・がんばればいけそうじゃないかなあ？", speaker:0, order:18)
Conversation.create!(level:6, content:"（えもん）ひとの話を聞いてたダ？", speaker:1, order:19)
